### ISSUE TITLE
When loading the graph, the following node types were not found

### ISSUE THREAD

**Issue by Tredicem** [cubiq/ComfyUI_InstantID#102]
![photo_2024-03-18_00-39-16](https://github.com/cubiq/ComfyUI_InstantID/assets/163758596/c7eea491-2169-4a66-835b-684e4ccda8b0)
 I just started to figure out comfyui and I don't know what to do with this error

**Comment by cubiq** [comment]
you need to check the extension installation. it's not properly installed

**Comment by Drivik** [comment]
I've also been struggling with this isse for 4+ hourrs and using portable version on ComfyUI instead of a StabilityMatrix one helped me. 
I installed insightface locally via github and used a wheel mentioned in the YouTube video from the comment below. 

https://github.com/cubiq/ComfyUI_InstantID/issues/9#issuecomment-1944124506

Let me know if it helps
