### ISSUE TITLE
Insightface installation failing in ComfyUI?

### ISSUE THREAD

**Issue by SNK6x** [cubiq/ComfyUI_InstantID#164]
Not sure what's going on but it looks like insightface installation is failing.

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: D:\Program Files\Stable Diffusion\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip

## Execute install/(de)activation script for 'D:\Program Files\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID'
 Collecting insightface
   Using cached insightface-0.7.3.tar.gz (439 kB)
   Installing build dependencies: started
   Installing build dependencies: finished with status 'done'
   Getting requirements to build wheel: started
   Getting requirements to build wheel: finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   Getting requirements to build wheel did not run successfully.
[!]   exit code: 1
[!]
[!]   [18 lines of output]
[!]   Traceback (most recent call last):
[!]     File "D:\Program Files\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
[!]       main()
[!]     File "D:\Program Files\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
[!]       json_out['return_val'] = hook(**hook_input['kwargs'])
[!]                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\Program Files\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
[!]       return hook(config_settings)
[!]              ^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\Program Files\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
[!]       return self._get_build_requires(config_settings, requirements=['wheel'])
[!]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\Program Files\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
[!]       self.run_setup()
[!]     File "D:\Program Files\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
[!]       exec(code, locals())
[!]     File "<string>", line 11, in <module>
[!]   ModuleNotFoundError: No module named 'Cython'
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: subprocess-exited-with-error
[!]
[!] Getting requirements to build wheel did not run successfully.
[!] exit code: 1
[!]
[!] See above for output.
[!]
[!] note: This error originates from a subprocess, and is likely not a problem with pip.
[!]
[!] [notice] A new release of pip is available: 23.3.2 -> 24.0
[!] [notice] To update, run: D:\Program Files\Stable Diffusion\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
install/(de)activation script failed: D:\Program Files\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID

[ComfyUI-Manager] Startup script completed.
#######################################################################

**Comment by SNK6x** [comment]
![Screenshot 2024-06-01 125636](https://github.com/cubiq/ComfyUI_InstantID/assets/129659803/57b033cd-120b-4b23-8ee6-873a1976f6ca)
Looks like this in the manager, tried every option still fails in the same way.

**Comment by cubiq** [comment]
always update pip first

maybe you just need to install Cython, anyway there's a lengthy thread on the ipadapter on how to install insightface https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/162

**Comment by Reign-in-blood** [comment]
If you encounter the following error while trying to install InsightFace for InstantID in ComfyUI:

`insightface-0.7.3-cp311-cp311-win_amd64_.whl is not a supported wheel on this platform`

Here is the procedure I used to successfully install InsightFace:

### Steps to Follow:

1. **Check the Python version in ComfyUI:**
   - Go to the `~/comfyui/python_embedded` folder and double-click on `python.exe`.
   - Note the version of Python (e.g., 3.09, 3.10, 3.11, or 3.12).

2. **Install the same version of Python on Windows:**
   - Make sure the version of Python installed on your Windows system matches the one in `~/comfyui/python_embedded`.
   - If it doesn't, download and install the correct version from [python.org](https://www.python.org/).

3. **Install InsightFace:**
   - Navigate to the folder where Python is installed on your system, typically:
     
`C:\Users\UserName\AppData\Local\Programs\Python\Python311`
     
   - Click on the address bar in File Explorer, type `cmd`, and press Enter to open a command prompt.
   - Run the following command to install InsightFace:
    
`.\python.exe -m pip install insightface`
    

4. **Copy the "insightface" folder to ComfyUI:**
   - After the installation, a folder named "insightface" should appear.
   - Copy this folder and paste it into `~/comfyui/python_embedded` in your ComfyUI installation.
   - Then, in this folder, open a command prompt by typing `cmd` in the address bar and run the following command:
     
`.\python.exe -m pip install insightface`
     

After this, InsightFace should be successfully installed, and you should be able to install and use InstantID without any issues!

**Comment by farhadrezaee910** [comment]
Thank you for your great advice, my problem is solved.

**Comment by magicrbl** [comment]
This is awesome, I followed the suggestions in this thread and also another thread having the problem resolved...finally I have Insightface installed... 

https://www.reddit.com/r/StableDiffusion/comments/1749kpk/problem_with_pip_install_insightface073_newbie/
" I encountered a problem where insightface was installed into my local python config instead of the embed. This is how I resolved it (posting it here in case anyone encounters the same issue):
Download the 'insightface-0.7.3-cp310-cp310-win_amd64.whl' file. Save it anywhere you want.
Locate your python_embeded folder.
Example: PATH\ComfyUI_windows_portable\python_embeded\

Install insightface using pip by executing the following command:
"PATH\ComfyUI_windows_portable\python_embeded\python.exe -m pip install PATH\insightface-0.7.3-cp310-cp310-win_amd64.whl"
Replace "PATH" with the actual paths on your system. Remember to swap insightface.whl to match the version you download.
3.10 https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp310-cp310-win_amd64.whl
3.11 https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl
" 
I run ComfyUI on Python 3.12.8 so I downloaded  [insightface-0.7.3-cp312-cp312-win_amd64.whl](https://github.com/Gourieff/Assets/blob/main/Insightface/insightface-0.7.3-cp312-cp312-win_amd64.whl) from https://github.com/Gourieff/Assets/tree/main/Insightface 

I hope this will help anyone who is having same or similar problem.... its really headaching, it took me a couple of hours working on it non stop...
