### ISSUE TITLE
A Thank You

### ISSUE THREAD

**Issue by camoody1** [cubiq/ComfyUI_InstantID#3]
Just wanted to thank you SO MUCH for this wonderful implementation of InstantID. I, like many, have been struggling to use the other two unofficial implementations since InstantID was released. Yours is such a smooth install and run. No memory errors. Just fast, good looking images. Well done.

Thank you

**Comment by LubuLubu2** [comment]
Me too, these guys rock, and i always welcome more optimizations and support specially if it's possible for SD 1.5.

Haven't even tried using other InstantID nods because of their v-ram requirements but with this nod i can. it's still puts my comfyui in low -vram mode (controlnet model will cause it in this case) which half it's generation speed but at 25step 40~ second is still a win. i'm on a 8gb gpu (3060ti)

**Comment by cubiq** [comment]
thanks for taking the time to write, guys. Really appreciate it.

if you have speed problems, try with Turbo, it works very well
